### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Sanesecurity** [Picocrypt/PicoGo#56]
1. Can't seem to find where you add a password.... Only key files shown.

2. Text box alignment slightly off

See Samsung a54 screenshot attached

![Image](https://github.com/user-attachments/assets/72b9609b-04d1-4358-b7cb-1cc65cb356b5)

**Comment by njhuffman** [comment]
Thanks for the feedback!

Something here looks cut off. The password entry is below the keyfiles. A couple questions/ideas:
1. Any chance that you can scroll down? I doubt it, but that would be an option if the device was intentionally hiding part of the window
2. Does the a54 have any display/accessibility settings for text size? The text size looks much larger than on my current test device (pixel 8).

Both of these are probably app issues, but fyne is _supposed_ to handle scaling naturally, so I would have expected this to just fit.

I could wrap the whole app in scrollable container internally, which would definitely let you scroll down to the password entry. But that is just hiding the scaling issue here somewhere, which I think is causing both of your issues.

**Comment by njhuffman** [comment]
For reference, here's a screenshot from my device. ![Screenshot_20250518-194333.png](https://github.com/user-attachments/assets/979165f3-bec5-43b2-bebe-3e37bf66cda5)

**Comment by njhuffman** [comment]
Okay, I think I sorted out the problem.
On my test device (android 15 on pixel 8), I can recreate this issue by changing `Settings > Display size and text > Display Size`. I've been developing with a minimized display size, and can get a near-identical view as reported when changing to the middle size option. No password entry visible, no ability to scroll down or scale the ui.

Not sure what the best way to handle this is yet, but I'll get something set up. The app should at a minimum be usable regardless of user preference for the rest of their device.

**Comment by Sanesecurity** [comment]
I've tried changed both the font size to small and tried changing the font itself ... but doesn't seem to change anything.

I can see a line at the bottom of the screen... but can't scroll down.

 Oneui 6.1. Android 14

**Comment by Sanesecurity** [comment]
Same screen  issue on an old redmi note 9 running Android 13, in case that helps

**Comment by njhuffman** [comment]
I think I've resolved this with release v0.1.4. Let me know if this is still an issue on that release.

**Comment by Sanesecurity** [comment]
Much much better... Just the letter y overlapping the line... 

![Image](https://github.com/user-attachments/assets/2fb3ddd4-cc7b-48a0-99d1-a2fd17af7707)

**Comment by njhuffman** [comment]
Good catch. Hm. I think v0.1.5 should fix it, but it looks the same on my device on both versions so not 100% sure.

**Comment by Sanesecurity** [comment]
Hi. Thanks for taking a look... Just tried 0.1.5 but still the same overlap....

![Image](https://github.com/user-attachments/assets/490e564a-a184-40df-9011-2bb09b5211ca)

**Comment by HACKERALERT** [comment]
Continue here: https://github.com/njhuffman/picogo/issues/5
